language: android

sudo: false

android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script: ./gradlew clean build --info
